import {mysqlTable, serial, varchar, text, boolean} from 'drizzle-orm/mysql-core';
export const coursesTable = mysqlTable('courses', {
    id: serial().primaryKey(),
    name: varchar({ length: 255 }),
    cover_url: varchar({ length: 255 }),
    start_date: varchar({ length: 50 }),
    end_date: varchar({ length: 50 }),
    time: varchar({ length: 100 }),
    time_description: varchar({ length: 100 }),
    duration: varchar({ length: 50 }),
    regime: varchar({ length: 100 }),
    location: varchar({ length: 255 }),
    description: text(),
    audience: text(),
    requirements: text(),
    project: varchar({ length: 255 }),
    price: varchar({ length: 50 }),
    benefits: text(),
    goals: text(),
    sponsor_img_url: varchar({ length: 255 }),
    course_content: text(),
    enrollment: varchar({ length: 100 }),
    has_download_button: boolean(),
});