import type {Course} from "shared/dist/types/course";

export const courses: Course[] = [
    {
        id: 1,
        name: "Gestor/Coordenador da Formação",
        coverUrl: "",
        startDate: new Date("2026-01-15"),
        endDate: new Date("2026-03-05"),
        time: "18:00 - 22:00",
        timeDescription: "Pós Laboral",
        duration: "50h",
        regime: "Online",
        location: "",
        description: "Os formadores são, atualmente, confrontados com a necessidade de assumir outro tipo de atividades para além da de formador, nomeadamente ao nível da gestão e coordenação de ações de formação o que exige a mobilização de um conjunto de competências técnicas, mas também sociais e relacionais, que implicam a aquisição de conhecimentos, capacidades e atitudes relacionadas com a conceção, planeamento, acompanhamento, gestão e avaliação de programas de formação. No contexto atual, os gestores de formação são os atores que “dão sentido” à formação, na medida em que estimulam a função crítica, desenvolvem dispositivos de formação e gerem as relações com o exterior (entidades, formandos, formadores, …). Certificado de Competências Pedagógicas de Especialização (CCPE) de Gestor/Coordenador de Formação.",
        audience: "A Formação Pedagógica Contínua de Formadores – Gestor/Coordenador de Formação é dirigida a indivíduos que pretendam adquirir o Certificado de Competências Pedagógicas de Especialização (CCPE) de Gestor/Coordenador de Formação para exercer atividades a nível da gestão, coordenação, acompanhamento, recrutamento e avaliação da formação presencial e/ou a distância.",
        requirements: "As condições de acesso à Formação Pedagógica Contínua de Formadores – Gestor/Coordenador de Formação exigem que os candidatos reúnam os seguintes requisitos:\nQualificação de nível superior;\nCertificado de Competências Pedagógicas (CCP) ou a exceção prevista no n.º 2 do artigo 2º da Portaria n.º 214/2011, de 30 de maio;\n100 horas, comprovadas, de experiência formativa enquanto Formador (independentemente do curso de formação);\nCompetências digitais, nomeadamente, processamento de texto (nível independente), criação de conteúdos (nível básico), comunicação (nível básico), resolução de problemas (nível básico) e segurança da informação (nível independente;\nExperiência profissional mínima de 3 anos.",
        project: "Formação de Formadores",
        price: "160,00€",
        benefits: "",
        goals: "Tendo em conta as finalidades expostas anteriormente, foram criadas condições para que, com esta formação os formandos possam:\nDistinguir as competências e funções do gestor/coordenador de formação em função dos contextos em que intervém;\nRealizar diagnósticos de necessidades de formação alinhados com as orientações estratégicas da entidade e com as políticas de formação políticas de formação das empresas/sectores/regiões;\nPlanear la formação com base nas necessidades identificadas das empresas/sectores/regiões;\nGerir e controlar financeiramente projetos de educação/formação;\nPromover e divulgar um plano/ação de formação;\nOrganizar, orientar, acompanhar e coordenar a formação e as equipas de trabalho;\nAdotar técnicas de gestão da formação, para administrar o dispositivo formativo da organização;\nGerir e coordenar ações de formação a distância;\nConhecer os modelos e orientações específicas para a qualidade da formação;\nDesenvolver um sistema de avaliação da formação que permita avaliar a qualidade, eficiência e eficácia do projeto formativo;\nImplementar sistemas de melhoria contínua da formação aplicando os métodos e as técnicas necessárias à otimização dos resultados das atividades de gestão e avaliação.",
        sponsorImgUrl: "",
        courseContent: "Nesta ação de formação, iremos apresentar um conjunto de conteúdos que proporcionarão aos formandos a oportunidade de adquirir competências essenciais para o seu desenvolvimento. Saiba aqui quais as temáticas que irão ser abordadas.",
        enrollment: "",
        hasDownloadButton: false
    },
    {
        id: 2,
        name: "Contabilidade e Secretariado Digital",
        coverUrl: "",
        startDate: new Date("2026-02-02"),
        endDate: new Date("2026-09-19"),
        time: "09:00 - 17:00",
        timeDescription: "Laboral",
        duration: "950h",
        regime: "Presencial",
        location: "Marco de Canaveses",
        description: "",
        audience: "Adultos desempregados, com mínimo de 12º ano, que pretendam desenvolver competências nas áreas de contabilidade administrativa e Office digital.",
        requirements: "",
        project: "#Digital Reskilling",
        price: "Gratuito",
        benefits: "Consulte aqui os beneficios inerentes a este curso.",
        goals: "Dotar os formandos de conhecimentos teóricos e competências técnicas que lhes permitam aplicar ferramentas informáticas associadas à automatização de tarefas digitais administrativas, tais como executar operações de processador de texto em ambientes online e offline, executar operações básicas de folha de cálculo em ambiente online\ne offline, criar e gerir sistemas de gestão de base de dados, bem como efetuar procedimentos de apoio à contabilidade geral em organizações públicas ou privadas.",
        sponsorImgUrl: "Este curso é financiado por entidades e planos governamentais.",
        courseContent: "",
        enrollment: "Inscrições Abertas",
        hasDownloadButton: true
    },
    {
        id: 3,
        name: "Digital Marketing & Business Strategy",
        coverUrl: "",
        startDate: new Date("2026-02-02"),
        endDate: new Date("2026-09-24"),
        time: "09:00 - 17:00",
        timeDescription: "Laboral",
        duration: "1000h",
        regime: "Presencial",
        location: "S. João da Madeira",
        description: "",
        audience: "Adultos desempregados, com mínimo de 12º ano, que pretendam desenvolver competências em Marketing Digital, Comércio Eletrónico, Internacionalização de Conteúdos e Estratégias de Negócio.",
        requirements: "",
        project: "#Digital Reskilling",
        price: "Gratuito",
        benefits: "Consulte aqui os beneficios inerentes a este curso.",
        goals: "Dotar os formandos de conhecimentos teóricos e competências técnicas para permitir conceber campanhas de marketing digital, criar conteúdos gráficos para o meio digital alinhados com as necessidades dos consumidores, gerir comunicação aproveitando as potencialidades das redes sociais e utilizar ferramentas de gestão estratégica empresarial.",
        sponsorImgUrl: "Este curso é financiado por entidades e planos governamentais.",
        courseContent: "",
        enrollment: "Inscrições Abertas",
        hasDownloadButton: true
    },
    {
        id: 4,
        name: "Formação Ped. Cont. Formador a Distância E-Formador (1ªEd.26)",
        coverUrl: "",
        startDate: new Date("2026-02-20"),
        endDate: new Date("2026-04-09"),
        time: "18:30 - 21:30",
        timeDescription: "Pós Laboral",
        duration: "60h",
        regime: "E Learning",
        location: "Leça ",
        description: "",
        audience: "Formadores, Gestores de Formação, Coordenadores de Formação, Técnicos de Formação, Professores e outros profissionais detentores do Certificado de Competências Pedagógicas de Formador (CCP), que pretendam adquirir o Certificado de Competências Pedagógicas de Especialização (CCPE) de e-formador.",
        requirements: "Qualificações de nível superior (preferencialmente);\nCertificado de Competências Pedagógicas (CCP);\n100 horas, comprovadas, de experiência formativa enquanto formador;\nCompetências digitais.",
        project: "Formação de Formadores",
        price: "Gratuito",
        benefits: "",
        goals: "No final deste Curso, os formandos deverão ser capazes de:\nDefinir o que é o Ensino a Distância (E-learnig e ambiente online);\nDesenvolver o design de cursos a distância;\nPlanear e desenvolver estratégias de avaliação rigorosas e adequadas ao tempo do curso/módulo;\nPlanear e desenvolver estratégias pedagógicas capazes de orientar e ajudar o formando a progredir no percurso de aprendizagem;\nSelecionar e criar os conteúdos digitais, que possam levar o formando a atingir os resultados de aprendizagem;\nImplementar e testar o seu curso com um ou mais colegas de grupo e refletir sobre a sua utilidade ou eficácia.",
        sponsorImgUrl: "",
        courseContent: "Nesta ação de formação, iremos apresentar um conjunto de conteúdos que proporcionarão aos formandos a oportunidade de adquirir competências essenciais para o seu desenvolvimento. Saiba aqui quais as temáticas que irão ser abordadas.",
        enrollment: "Inscrições Abertas",
        hasDownloadButton: false
    },
    {
        id: 5,
        name: "Análise de Dados (1ª Ed.)",
        coverUrl: "",
        startDate: new Date("2026-03-02"),
        endDate: new Date("2026-07-02"),
        time: "18:30 - 21:30",
        timeDescription: "Pós Laboral",
        duration: "300h",
        regime: "E Learning",
        location: "Leça ",
        description: "",
        audience: "Os destinatários são os jovens adultos, com idade igual ou superior a 18 anos e menor ou igual a 35 anos, desempregados, com habilitação de nível secundário ou superior.",
        requirements: "Computador com microfone, câmara e acesso à Internet.",
        project: "Jovem +Digital",
        price: "Gratuito",
        benefits: "Consulte aqui os beneficios inerentes a este curso.",
        goals: "Aplicar ferramentas informáticas associadas à recolha, armazenamento, acesso e processamento de dados para a produção de informação de suporte à tomada de decisão e consequente ação;\nDesenvolver competências de base no acesso, extração, limpeza, transformação e carregamento de dados que suportam o desenvolvimento de modelos de apoio à decisão;\nDesenvolver competências básicas na exploração de dados e no desenvolvimento de modelos analíticos de apoio à tomada de decisão.",
        sponsorImgUrl: "Este projeto é financiado por entidades e planos governamentais.",
        courseContent: "Nesta ação de formação, iremos apresentar um conjunto de conteúdos que proporcionarão aos formandos a oportunidade de adquirir competências essenciais para o seu desenvolvimento. Saiba aqui quais as temáticas que irão ser abordadas.",
        enrollment: "Inscrições Abertas",
        hasDownloadButton: false
    },
    {
        id: 6,
        name: "Data Science and Analytics",
        coverUrl: "",
        startDate: new Date("2026-03-16"),
        endDate: new Date("2026-10-28"),
        time: "09:00 - 17:00",
        timeDescription: "Laboral",
        duration: "950h",
        regime: "Presencial",
        location: "S. João da Madeira",
        description: "",
        audience: "Adultos desempregados, com mínimo de 12º ano, que pretendam desenvolver competências associadas à produção e análise de informação de apoio à tomada de decisão.",
        requirements: "",
        project: "#Digital Reskilling",
        price: "Gratuito",
        benefits: "Consulte aqui os beneficios inerentes a este curso.",
        goals: "Dotar os formandos de conhecimentos teóricos e competências técnicas necessários para ingressar no mercado de trabalho numa atividade profissional ligada à Análise de Dados e Business Intelligence: extração, transformação e carregamento de dados; produção de informação de apoio à tomada de decisão e desenvolvimento de modelos analíticos; construção de relatórios e dashboards com métricas de negócio.",
        sponsorImgUrl: "Este curso é financiado por entidades e planos governamentais.",
        courseContent: "",
        enrollment: "Inscrições abrem em fevereiro de 2026.",
        hasDownloadButton: true
    },
    {
        id: 7,
        name: "Digital Office",
        coverUrl: "",
        startDate: new Date("2026-03-16"),
        endDate: new Date("2026-10-28"),
        time: "09:00 - 17:00",
        timeDescription: "Laboral",
        duration: "950h",
        regime: "Presencial",
        location: "Vila do Conde",
        description: "",
        audience: "Adultos desempregados, com mínimo de 12º ano, que pretendam desenvolver competências em Digital Office, Comércio Eletrónico, Apoio Administrativo e Estratégias de Negócio.",
        requirements: "",
        project: "#Digital Reskilling",
        price: "Gratuito",
        benefits: "Consulte aqui os beneficios inerentes a este curso.",
        goals: "Dotar os formandos de conhecimentos teóricos e competências técnicas para permitir efetuar procedimentos administrativos tais como trabalhar em mail marketing, digitalização de documentos, comércio eletrónico, preparar informação para projetar dashboards, trabalhar com plataformas de informação de apoio à gestão operacional da empresa, bem como efetuar procedimentos de apoio à contabilidade geral e nas aplicações informáticas de gestão.",
        sponsorImgUrl: "Este curso é financiado por entidades e planos governamentais.",
        courseContent: "",
        enrollment: "Inscrições Abertas",
        hasDownloadButton: true
    },
    {
        id: 8,
        name: "Software Developer (PRT)",
        coverUrl: "",
        startDate: new Date("2026-03-23"),
        endDate: new Date("2026-12-03"),
        time: "09:00 - 17:00",
        timeDescription: "Laboral",
        duration: "1050h",
        regime: "Presencial",
        location: "Porto",
        description: "Sabias que um software developer pode trabalhar em/e para qualquer parte do mundo?\nSabias que a profissão de software developer é uma das profissões com maior taxa de empregabilidade e salários competitivos?\n\nPRO_MOV by Reskilling 4 Employment\n\nIntegrado no laboratório digital do projeto Reskilling 4 Employment, este programa de formação Software Developer, pretende promover a requalificação profissional de jovens e adultos e capacitar profissionais para o domínio técnico especializado em temáticas relacionadas com a programação e desenvolvimento de plataformas web e mobile, gestão de bases de dados e engenharia de software. Inclui ainda formação prática em contexto de trabalho com objetivo de dotar especialistas para integrar o mercado empresarial.\nSão parceiras as empresas SAP, BPI, Fidelidade, Sonae, Millennium, Galp, CTT, Bosh, Manpower, Altice e Grupo Simoldes que unem esforços para concretizar este projeto.",
        audience: "Adultos, empregados ou desempregados, com mínimo de 12º ano e domínio da língua inglesa ao nível intermédio, que pretendam desenvolver competências para desenvolvimento de sistemas e plataformas web e aplicações mobile.",
        requirements: "",
        project: "Reskilling 4 Employment",
        price: "Gratuito",
        benefits: "Consulte aqui os beneficios inerentes a este curso.",
        goals: "Dotar os formandos de conhecimentos teóricos e competências técnicas necessários para ingressar no mercado de trabalho numa atividade profissional ligada à Programação Web e Mobile: definição de arquiteturas de software e bases de dados, desenvolvimento de plataformas web client-side e server-side, criação e manutenção de aplicações mobile, gestão de projetos em metodologias waterfall e agile.",
        sponsorImgUrl: "Este curso é financiado por entidades e planos governamentais.",
        courseContent: "",
        enrollment: "Abertura de inscrições em fevereiro.",
        hasDownloadButton: true
    },
    {
        id: 9,
        name: "UI/UX Development",
        coverUrl: "",
        startDate: new Date("2026-04-07"),
        endDate: new Date("2026-11-09"),
        time: "09:00 - 17:00",
        timeDescription: "Laboral",
        duration: "950h",
        regime: "Presencial",
        location: "Leça da Palmeira",
        description: "O curso de UX / UI Development prepara técnicos com mínimo nível III, que pretendem ser profissionais na construção visual de qualquer plataforma, nomeadamente em projetos de websites, aplicações para desktop, web apps, banners, sistemas e até mesmo interfaces em dispositivos móveis. Dado que as nossas vidas dependem atualmente da interação com a tecnologia, este é um fator que está a fazer com que esta profissão esteja a ser bastante procurada no mercado. A área do UI (User Interface) é responsável pela parte visual de um projeto e UX (User Experience) é a área do design que vai além dos aspetos visuais de uma plataforma, garantindo que ela seja, de forma geral, simples, intuitiva e até mesmo interessante de ser utilizada pelo utilizador. São áreas do design que podem (e devem) ser utilizadas juntas para obter resultados ainda melhores, apesar de terem abordagens distintas.\n",
        audience: "Adultos desempregados, com mínimo de 12º ano, que pretendam desenvolver competências para planeamento, conceção e desenvolvimento de interfaces com estudo de usabilidade.",
        requirements: "",
        project: "#Digital Reskilling",
        price: "Gratuito",
        benefits: "Consulte aqui os beneficios inerentes a este curso.",
        goals: "Dotar os formandos de conhecimentos teóricos e competências técnicas necessários para ingressar no mercado de trabalho numa atividade profissional relacionada com o planeamento e desenho de interfaces gráficas, com foco na usabilidade, experiência de navegação e interação do utilizador com plataformas digitais, bem como  desenvolvimento (client-side) de plataformas web.",
        sponsorImgUrl: "Este curso é financiado por entidades e planos governamentais.",
        courseContent: "",
        enrollment: "Inscrições Abertas",
        hasDownloadButton: true
    },
    {
        id: 10,
        name: "Network & Cyber Security Administrator (LIS)",
        coverUrl: "",
        startDate: new Date("2026-04-08"),
        endDate: new Date("2026-12-21"),
        time: "09:00 - 17:00",
        timeDescription: "Laboral",
        duration: "1100h",
        regime: "B Learning",
        location: "Lisboa",
        description: "",
        audience: "Adultos, com mínimo de 12º ano, que pretendam desenvolver competências em Gestão de Redes, Instalação e Manutenção de Sistemas Informáticos e Cibersegurança.",
        requirements: "",
        project: "Reskilling 4 Employment",
        price: "Gratuito",
        benefits: "Consulte aqui os beneficios inerentes a este curso.",
        goals: "Dotar os formandos de conhecimentos teóricos e competências técnicas necessários para ingressar no mercado de trabalho numa atividade profissional ligada à Administração de Redes e/ou Cibersegurança: implementar, gerir e manter redes informáticas e sistemas operativos servidores, atuar preventivamente contra ameaças cibernéticas, criar, extrair e analisar scripts para análise de vulnerabilidades, identificar fragilidades em plataformas web, interpretar a legislação sobre segurança e privacidade dos dados, utilizar ferramentas de análise de incidentes e conceção de relatórios críticos.",
        sponsorImgUrl: "Este curso é financiado por entidades e planos governamentais.",
        courseContent: "",
        enrollment: "Inscrições abrem em fevereiro de 2026.",
        hasDownloadButton: true
    },
    {
        id: 11,
        name: "Creative Digital Media - Games Edition",
        coverUrl: "",
        startDate: new Date("2026-04-13"),
        endDate: new Date("2026-12-31"),
        time: "09:00 - 17:00",
        timeDescription: "Laboral",
        duration: "1100h",
        regime: "Presencial",
        location: "Porto",
        description: "Aprendizagem prática e orientada para as exigências do mercado de trabalho;\nAcesso a tecnologias inovadoras, como ferramentas de inteligência artificial e softwares de design de jogos;\nFormação abrangente que integra produção multimédia e desenvolvimento de videojogos;\nCertificação reconhecida que abre portas para uma carreira no setor criativo digital.\nUma formação que une criatividade, tecnologia e ética, preparando profissionais para os desafios e oportunidades do futuro digital.",
        audience: "Este curso é direcionado a adultos desempregados, com habilitações mínimas ao nível do 12.º ano de escolaridade, que pretendam:\nDesenvolver competências em fotografia, vídeo, animação e design gráfico;\nAprender a desenhar e criar videojogos 2D e 3D;\nExplorar as possibilidades criativas de ferramentas baseadas em inteligência artificial;\nConstruir uma carreira sólida e inovadora nas áreas da multimédia e do desenvolvimento de jogos.",
        requirements: "",
        project: "#Digital Reskilling",
        price: "Gratuito",
        benefits: "Consulte aqui os beneficios inerentes a este curso.",
        goals: "O curso Creative Digital Media – Games Edition oferece uma formação completa e inovadora, que combina competências tradicionais de produção multimédia com as mais recentes tecnologias digitais. Agora com uma componente dedicada ao Game Design e Development, o curso prepara os formandos para:\nPlanear, captar e editar imagem e vídeo com qualidade profissional;\nCriar animações dinâmicas, arte digital e sincronizar elementos visuais e sonoros;\nDominar técnicas de design e desenvolvimento de videojogos 2D e 3D, aplicando conceitos de narrativa interativa, design de níveis e mecânicas de jogo;\nExplorar as possibilidades criativas de ferramentas de última geração, incluindo inteligência artificial, para impulsionar projetos multimédia;\nTrabalhar de forma ética e responsável, respeitando a propriedade intelectual e as melhores práticas na criação digital.",
        sponsorImgUrl: "Este curso é financiado por entidades e planos governamentais.",
        courseContent: "",
        enrollment: "",
        hasDownloadButton: true
    },
    {
        id: 12,
        name: "Programador/a Low Code (LIS)",
        coverUrl: "",
        startDate: new Date("2026-05-05"),
        endDate: new Date("21/01/2027"),
        time: "09:00 - 17:00 | 14:00-22:00",
        timeDescription: "Laboral",
        duration: "1100h",
        regime: "B Learning",
        location: "Lisboa",
        description: "Sabias que ser Programador/a Low Code é atualmente uma profissão muito procurada, com excelentes oportunidades de carreira e salários competitivos?\nSabias que a plataforma OutSystems, criada em Portugal, é usada por empresas em todo o mundo para desenvolver aplicações de forma rápida e inovadora?\n\nPRO_MOV by Reskilling 4 Employment\nIntegrado no laboratório do Business Intelligence do projeto Reskilling 4 Employment, o programa de formação Programador/a Low Code tem como objetivo requalificar jovens e adultos, preparando-os para uma das áreas tecnológicas com maior crescimento.\n\nVais aprender a criar aplicações web e mobile de forma visual, bem como fluxos de processos empresariais, utilizando a plataforma OutSystems. Terás também formação prática em contexto real de trabalho, para que possas aplicar as tuas competências num ambiente empresarial. Várias empresas parceiras unem esforços para te ajudar a dar o salto para o mercado de trabalho.",
        audience: "Adultos, com mínimo de 12.º ano e nível intermédio de inglês, que pretendam desenvolver competências em programação Low-Code, automação de processos e criação de soluções digitais que respondam às necessidades das empresas.",
        requirements: "Computador com microfone, câmara e acesso à Internet.",
        project: "Reskilling 4 Employment",
        price: "Gratuito",
        benefits: "Consulte aqui os beneficios inerentes a este curso.",
        goals: "Capacitar os formandos com os conhecimentos teóricos e práticos necessários para entrarem no mercado de trabalho como profissionais em desenvolvimento Low-Code, capazes de:\nAnalisar, modelar, criar e otimizar aplicações web e mobile na plataforma OutSystems;\nAutomatizar processos empresariais;\nColaborar em equipas de desenvolvimento ágil;\nAcompanhar as necessidades tecnológicas das empresas, contribuindo para a sua transformação digital.",
        sponsorImgUrl: "Este curso é financiado por entidades e planos governamentais.",
        courseContent: "",
        enrollment: "Inscrições abrem em março de 2026.",
        hasDownloadButton: true
    },
    {
        id: 13,
        name: "AWS RE/START - Cloud Computing",
        coverUrl: "",
        startDate: new Date("2026-06-01"),
        endDate: new Date("2026-10-09"),
        time: "09:00 - 17:00",
        timeDescription: "Laboral",
        duration: "600h",
        regime: "B Learning",
        location: "Leça da Palmeira",
        description: "Estás pronto para impulsionar a tua carreira na nuvem? O AWS re/Start é um programa de formação em competências de nuvem da Amazon Web Services (AWS), que prepara jovens e adultos para carreiras em computação em nuvem.\n\nO AWS re/Start é um programa de desenvolvimento de talentos e de formação profissional a tempo inteiro, que prepara indivíduos para carreiras em computação em nuvem e os liga a potenciais empregadores. Através de uma aprendizagem baseada em cenários reais, laboratórios práticos e cursos teóricos, os formandos aprendem competências de Linux, Python, Redes, Segurança e Bases de Dados Relacionais, além de se prepararem para o exame de certificação AWS Certified Cloud Practitioner. O programa também oferece apoio na preparação para o mercado de trabalho, como a elaboração de currículos e simulação de entrevistas.\nO programa é gratuito para os formandos e foca-se em desempregados ou subempregados.",
        audience: "Adultos, desempregados ou subempregados, com habilitação mínima ao nível do 12.º ano, bons conhecimentos de inglês e forte motivação para iniciar uma carreira na área da tecnologia.",
        requirements: "",
        project: "#Digital Reskilling",
        price: "Gratuito",
        benefits: "Consulte aqui os beneficios inerentes a este curso.",
        goals: "No final do curso, os formandos serão capazes de:\nDominar conceitos fundamentais de computação em nuvem, arquitetura AWS e serviços principais;\nUtilizar sistemas operativos Linux e linguagens de programação como Python;\nCompreender e aplicar conceitos de redes e segurança no contexto de nuvem;\nGerir bases de dados relacionais;\nEstar aptos a realizar o exame de certificação AWS Certified Cloud Practitioner;\nDemonstrar competências de comunicação, resolução de problemas e trabalho em equipa fundamentais para o sucesso profissional.",
        sponsorImgUrl: "Este curso é financiado por entidades e planos governamentais.",
        courseContent: "",
        enrollment: "Inscrições abrem em abril de 2026.",
        hasDownloadButton: true
    },
    {
        id: 14,
        name: "Data Analyst",
        coverUrl: "",
        startDate: new Date("2026-06-17"),
        endDate: new Date("12/03/2027"),
        time: "09:00 - 17:00",
        timeDescription: "Laboral",
        duration: "1100h",
        regime: "B Learning",
        location: "Lisboa",
        description: "Sabias que a profissão de Data Analyst é uma profissão desafiadora e com salários competitivos?\nSabias que um Data Analyst tem inúmeras oportunidades de crescimento profissional e elevada facilidade de integração no mercado de trabalho?\n\nPRO_MOV by Reskilling 4 Employment\nIntegrado no laboratório do Business Intelligence do projeto Reskilling 4 Employment, este programa de formação Data Analyst, pretende promover a requalificação profissional de jovens e adultos e capacitar profissionais para o domínio técnico especializado na recolha, organização e interpretação de dados, identificando tendências e ajudando as empresas na tomada de decisões. Inclui ainda formação prática em contexto de trabalho com o objetivo de dotar especialistas para integrar o mercado empresarial. São várias as empresas parceiras que unem esforços para concretizar este projeto.\n",
        audience: "Adultos, empregados ou desempregados, com mínimo de 12º ano e domínio da língua inglesa ao nível intermédio, que pretendam desenvolver competências para a criação de modelos e algoritmos que permitam recolher, analisar e extrair informação útil de grandes quantidades de dados.",
        requirements: "",
        project: "Reskilling 4 Employment",
        price: "Gratuito",
        benefits: "Consulte aqui os beneficios inerentes a este curso.",
        goals: "Dotar os formandos de conhecimentos teóricos e competências técnicas necessários para ingressar no mercado de trabalho numa atividade profissional ligada ao desenvolvimento de modelos, algoritmos e técnicas que permitam a recolha, a organização, a análise e a manipulação de grandes quantidades de informação, procurando padrões e tentando obter informação útil e pertinente para a tomada de decisões e para o crescimento das empresas.",
        sponsorImgUrl: "Este curso é financiado por entidades e planos governamentais.",
        courseContent: "",
        enrollment: "Inscrições abrem em abril 2026.",
        hasDownloadButton: true
    },
    {
        id: 15,
        name: "Data Analyst (PRT)",
        coverUrl: "",
        startDate: new Date("2026-06-17"),
        endDate: new Date("12/03/2027"),
        time: "09:00 - 17:00",
        timeDescription: "Laboral",
        duration: "1100h",
        regime: "Presencial",
        location: "Porto",
        description: "Sabias que a profissão de Data Analyst é uma profissão desafiadora e com salários competitivos?\nSabias que um Data Analyst tem inúmeras oportunidades de crescimento profissional e elevada facilidade de integração no mercado de trabalho?\n\nPRO_MOV by Reskilling 4 Employment\nIntegrado no laboratório do Business Intelligence do projeto Reskilling 4 Employment, este programa de formação Data Analyst, pretende promover a requalificação profissional de jovens e adultos e capacitar profissionais para o domínio técnico especializado na recolha, organização e interpretação de dados, identificando tendências e ajudando as empresas na tomada de decisões. Inclui ainda formação prática em contexto de trabalho com o objetivo de dotar especialistas para integrar o mercado empresarial. São várias as empresas parceiras que unem esforços para concretizar este projeto.",
        audience: "Adultos, empregados ou desempregados, com mínimo de 12º ano e domínio da língua inglesa ao nível intermédio, que pretendam desenvolver competências para a criação de modelos e algoritmos que permitam recolher, analisar e extrair informação útil de grandes quantidades de dados.",
        requirements: "",
        project: "Reskilling 4 Employment",
        price: "Gratuito",
        benefits: "Consulte aqui os beneficios inerentes a este curso.",
        goals: "Dotar os formandos de conhecimentos teóricos e competências técnicas necessários para ingressar no mercado de trabalho numa atividade profissional ligada ao desenvolvimento de modelos, algoritmos e técnicas que permitam a recolha, a organização, a análise e a manipulação de grandes quantidades de informação, procurando padrões e tentando obter informação útil e pertinente para a tomada de decisões e para o crescimento das empresas.",
        sponsorImgUrl: "Este curso é financiado por entidades e planos governamentais.",
        courseContent: "",
        enrollment: "Abertura de inscrições em abril.",
        hasDownloadButton: true
    },
    {
        id: 16,
        name: "Digital Office",
        coverUrl: "",
        startDate: new Date("2026-09-14"),
        endDate: new Date("13/4/2027"),
        time: "09:00 - 17:00",
        timeDescription: "Laboral",
        duration: "950h",
        regime: "Presencial",
        location: "Marco Canaveses",
        description: "",
        audience: "Adultos desempregados, com mínimo de 12º ano, que pretendam desenvolver competências em Digital Office, Comércio Eletrónico, Apoio Administrativo e Estratégias de Negócio.",
        requirements: "",
        project: "#Digital Reskilling",
        price: "Gratuito",
        benefits: "Consulte aqui os beneficios inerentes a este curso.",
        goals: "Dotar os formandos de conhecimentos teóricos e competências técnicas para permitir efetuar procedimentos administrativos tais como trabalhar em mail marketing, digitalização de documentos, comércio eletrónico, preparar informação para projetar dashboards, trabalhar com plataformas de informação de apoio à gestão operacional da empresa, bem como efetuar procedimentos de apoio à contabilidade geral e nas aplicações informáticas de gestão.",
        sponsorImgUrl: "Este curso é financiado por entidades e planos governamentais.",
        courseContent: "",
        enrollment: "Inscrições abrem em julho de 2026.",
        hasDownloadButton: true
    },
    {
        id: 17,
        name: "Software Developer",
        coverUrl: "",
        startDate: new Date("2026-09-22"),
        endDate: new Date("17/05/2027"),
        time: "09:00 - 17:00",
        timeDescription: "Laboral",
        duration: "1050h",
        regime: "B Learning",
        location: "Lisboa",
        description: "Sabias que um software developer pode trabalhar em/e para qualquer parte do mundo?\nSabias que a profissão de software developer é uma das profissões com maior taxa de empregabilidade e salários competitivos?\n\nPRO_MOV by Reskilling 4 Employment\n\nIntegrado no laboratório digital do projeto Reskilling 4 Employment, este programa de formação Software Developer, pretende promover a requalificação profissional de jovens e adultos e capacitar profissionais para o domínio técnico especializado em temáticas relacionadas com a programação e desenvolvimento de plataformas web e mobile, gestão de bases de dados e engenharia de software. Inclui ainda formação prática em contexto de trabalho com objetivo de dotar especialistas para integrar o mercado empresarial.\nSão parceiras as empresas SAP, BPI, Fidelidade, Sonae, Millennium, Galp, CTT, Bosh, Manpower, Altice e Grupo Simoldes que unem esforços para concretizar este projeto.",
        audience: "Adultos, empregados ou desempregados, com mínimo de 12º ano e domínio da língua inglesa ao nível intermédio, que pretendam desenvolver competências para desenvolvimento de sistemas e plataformas web e aplicações mobile.",
        requirements: "",
        project: "Reskilling 4 Employment",
        price: "Gratuito",
        benefits: "Consulte aqui os beneficios inerentes a este curso.",
        goals: "Dotar os formandos de conhecimentos teóricos e competências técnicas necessários para ingressar no mercado de trabalho numa atividade profissional ligada à Programação Web e Mobile: definição de arquiteturas de software e bases de dados, desenvolvimento de plataformas web client-side e server-side, criação e manutenção de aplicações mobile, gestão de projetos em metodologias waterfall e agile.",
        sponsorImgUrl: "Este curso é financiado por entidades e planos governamentais.",
        courseContent: "",
        enrollment: "",
        hasDownloadButton: true
    },
    {
        id: 18,
        name: "Técnico Especialista em Aplicações Informáticas de Gestão",
        coverUrl: "",
        startDate: new Date("2026-10-01"),
        endDate: new Date("31/10/2027"),
        time: "09:00 - 17:00",
        timeDescription: "Laboral",
        duration: "950h",
        regime: "Presencial",
        location: "Marco Canaveses",
        description: "",
        audience: "Jovens e adultos desempregados com idade compreendida entre os 18 e os 29 anos (inclusive), com uma das seguintes habilitações:\nCurso de ensino secundário, ou habilitação legalmente equivalente.\nNível básico de educação e que estejam a frequentar uma modalidade de educação ou formação ou um processo de reconhecimento, validação e certificação de competências de nível secundário.\nDiploma ou certificado de nível 5 de qualificação do QNQ, ou diploma de especialização tecnológica, ou grau ou diploma de ensino superior.",
        requirements: "",
        project: "Aprendizagem +",
        price: "Gratuito",
        benefits: "Consulte aqui os beneficios inerentes a este curso.",
        goals: "Manusear aplicações informáticas de apoio às diversas vertentes da gestão.\nPlanear, instalar e configurar sistemas e equipamentos informáticos e de redes estruturadas.\nApoiar a gestão da informação da organização, instalando, configurando e operando com aplicações de gestão documental que suportem a digitalização dos processos organizacionais;\nInstalar, configurar e operar com sistemas de comunicação e colaboração interna e externa.\nDesenhar e implementar páginas Web;\nInstalar, configurar e operar sistemas de gestão de conteúdos de suporte à sua presença na Web e nas redes sociais;\nDesenvolver e operar sistemas de informação simples modelando processos organizacionais e desenhando os correspondentes modelos de dados, de atividades e de gestão de fluxo de trabalho bem como os correspondentes modelos de interface;\nProduzir relatórios estatísticos, gráficos e painéis de controlo (dashboards) sobre as bases de dados.",
        sponsorImgUrl: "Este curso é financiado por entidades e planos governamentais.",
        courseContent: "",
        enrollment: "Inscrições abrem em agosto de 2026.",
        hasDownloadButton: true
    },
    {
        id: 19,
        name: "Técnico Especialista em Gestão de Redes e Sistemas Informáticos",
        coverUrl: "",
        startDate: new Date("2026-10-06"),
        endDate: new Date("31/10/2027"),
        time: "09:00 - 17:00",
        timeDescription: "Laboral",
        duration: "1585h",
        regime: "Presencial",
        location: "Porto",
        description: "Planear, executar, gerir e configurar infraestruturas de sistemas informáticos de apoio às diferentes áreas de gestão da organização bem como de suporte a redes de telecomunicações de nova geração, com integração de serviços de voz, dados e vídeo.",
        audience: "Jovens e adultos desempregados com idade compreendida entre os 18 e os 29 anos (inclusive), com uma das seguintes habilitações:\nCurso de ensino secundário, ou habilitação legalmente equivalente.\nNível básico de educação e que estejam a frequentar uma modalidade de educação ou formação ou um processo de reconhecimento, validação e certificação de competências de nível secundário.\nDiploma ou certificado de nível 5 de qualificação do QNQ, ou diploma de especialização tecnológica, ou grau ou diploma de ensino superior.",
        requirements: "",
        project: "Aprendizagem +",
        price: "Gratuito",
        benefits: "Consulte aqui os beneficios inerentes a este curso.",
        goals: "Instalar e configurar redes de comunicação, ao nível da infraestrutura de cablagem, do sistema operativo, do equipamento e dos serviços, dando especial realce às questões de desempenho e segurança;\nInstalar e configurar infraestruturas de rede baseadas num sistema operativo, usando a tecnologia mais ajustada;\nDimensionar e implementar uma rede corporativa de nova geração, com integração de serviços de voz, dados e vídeo;\nGerir e configurar sistemas de informação de suporte aos sistemas e redes de comunicações, nomeadamente, sistemas de supervisão e servidores de DHCP, DNS, NAS, Proxys, gestores de tráfego, entre outros;\nApoiar e gerir redes: protocolos e aplicações; servidores de autenticação, autorização, registo e contabilização;\nApoiar e gerir sistemas: modelos e aplicações, ferramentas, sistemas operativos, políticas de back up, redundância e fiabilidade, preparação de planos de emergência, estipular tolerância a falhas;\nApoiar e gerir serviços informáticos: políticas de licenciamento, suporte e manutenção, apoio aos utilizadores (helpdesk), ferramentas de apoio à instalação, diagnóstico, gestão e recuperação da informação;\nInstalar e configurar sistemas operativos, servidores, serviços e periféricos da rede;\nGerir e configurar servidores e serviços baseados na Internet.\nGerir utilizadores e computadores de forma centralizada.",
        sponsorImgUrl: "Este curso é financiado por entidades e planos governamentais.",
        courseContent: "",
        enrollment: "Inscrições abrem em agosto de 2026.",
        hasDownloadButton: true
    },
    {
        id: 20,
        name: "Software Developer",
        coverUrl: "",
        startDate: new Date("2026-10-21"),
        endDate: new Date("08/06/2027"),
        time: "09:00 - 17:00",
        timeDescription: "Laboral",
        duration: "1050h",
        regime: "Presencial",
        location: "Porto",
        description: "Sabias que um software developer pode trabalhar em/e para qualquer parte do mundo?\nSabias que a profissão de software developer é uma das profissões com maior taxa de empregabilidade e salários competitivos?\n\nPRO_MOV by Reskilling 4 Employment\n\nIntegrado no laboratório digital do projeto Reskilling 4 Employment, este programa de formação Software Developer, pretende promover a requalificação profissional de jovens e adultos e capacitar profissionais para o domínio técnico especializado em temáticas relacionadas com a programação e desenvolvimento de plataformas web e mobile, gestão de bases de dados e engenharia de software. Inclui ainda formação prática em contexto de trabalho com objetivo de dotar especialistas para integrar o mercado empresarial.\nSão parceiras as empresas SAP, BPI, Fidelidade, Sonae, Millennium, Galp, CTT, Bosh, Manpower, Altice e Grupo Simoldes que unem esforços para concretizar este projeto.",
        audience: "Adultos, empregados ou desempregados, com mínimo de 12º ano e domínio da língua inglesa ao nível intermédio, que pretendam desenvolver competências para desenvolvimento de sistemas e plataformas web e aplicações mobile.",
        requirements: "",
        project: "Reskilling 4 Employment",
        price: "Gratuito",
        benefits: "Consulte aqui os beneficios inerentes a este curso.",
        goals: "Dotar os formandos de conhecimentos teóricos e competências técnicas necessários para ingressar no mercado de trabalho numa atividade profissional ligada à Programação Web e Mobile: definição de arquiteturas de software e bases de dados, desenvolvimento de plataformas web client-side e server-side, criação e manutenção de aplicações mobile, gestão de projetos em metodologias waterfall e agile.",
        sponsorImgUrl: "Este curso é financiado por entidades e planos governamentais.",
        courseContent: "",
        enrollment: "Inscrições abrem em setembro de 2026.",
        hasDownloadButton: true
    },
    {
        id: 21,
        name: "Formação Pedagógica Inicial de Formadores - BLearning",
        coverUrl: "",
        startDate: new Date("2026-02-09"),
        endDate: new Date("2026-04-29"),
        time: "18:00 - 22:00",
        timeDescription: "Pós Laboral",
        duration: "90h",
        regime: "B Learning",
        location: "Leça",
        description: "A formação pedagógica inicial de formadores/as visa promover a aquisição, atualização e o aperfeiçoamento de competências, transferíveis para a sua prática na formação.",
        audience: "Os candidatos devem deter uma qualificação de nível superior ou ser detentores de uma habilitação mínima correspondente ao 12.º ano, mas com experiência profissional comprovada de 5 ou mais anos.",
        requirements: "Computador com microfone, câmara e acesso à Internet.",
        project: "Formação de Formadores",
        price: "Gratuito",
        benefits: "Consulte aqui os beneficios inerentes a este curso.",
        goals: "Identificar os elementos constituintes de um programa de formação;\nRedigir objetivos pedagógicos em termos operacionais, formulando objetivos de competências e de aprendizagem;\nDefinir e organizar os conteúdos programáticos;\nDeterminar a duração global do programa;\nDefinir estratégias, métodos e técnicas de aprendizagem e de avaliação;\nDefinir o regime/formato de formação (presencial, a distância, entre outros);\nSelecionar recursos técnico-pedagógicos;\nElaborar um plano de sessão;\nSelecionar e aplicar técnicas e métodos pedagógicos que facilitem o processo de aprendizagem e o desenvolvimento de competências;\nAplicar técnicas para uma comunicação eficaz, assertiva e facilitadora do processo de formação-aprendizagem;\nIdentificar e aplicar dinâmicas de grupo que fomentem a participação no processo de aprendizagem;\nAplicar ferramentas e plataformas digitais facilitadoras do processo de formação-aprendizagem;\nIdentificar, distinguir e adequar os diferentes tipos e técnicas de avaliação ao contexto;\nDefinir critérios de avaliação e escalas de classificação;\nConceber e aplicar instrumentos de acompanhamento e avaliação das aprendizagens e da qualidade e satisfação da formação.",
        sponsorImgUrl: "Este curso é financiado por entidades e planos governamentais.",
        courseContent: "",
        enrollment: "Turma Completa",
        hasDownloadButton: false
    },
    {
        id: 22,
        name: "Machine Learning com Python - Introdução",
        coverUrl: "",
        startDate: new Date("2026-01-13"),
        endDate: new Date("2026-03-13"),
        time: "19:00 - 23:00 (3ª, 4ª, 6ª)",
        timeDescription: "Pós Laboral",
        duration: "100h",
        regime: "Online",
        location: "",
        description: "O objetivo do curso é dotar os formandos de competências fundamentais em programação com Python e análise exploratória de dados, incluindo limpeza, transformação e visualização de dados. O curso tem uma forte componente prática e é especialmente concebido para participantes sem experiência prévia em programação, promovendo uma aprendizagem progressiva desde os conceitos básicos até à construção de pequenos dashboards e relatórios de análise aplicáveis em contextos reais.\n",
        audience: "Ativos empregados com o 12º ano, residentes nas zonas norte e centro do país.",
        requirements: "Computador com microfone, câmara e acesso à Internet.",
        project: "Formações Modulares",
        price: "Gratuito",
        benefits: "Consulte aqui os beneficios inerentes a este curso.",
        goals: "Dominar os conceitos basilares da programação utilizando a linguagem Python;\nImplementar lógica de controlo em programas através de estruturas de decisão e de repetição;\nUtilizar e manipular as principais estruturas de dados em Python, incluindo listas, dicionários, tuplos e conjuntos;\nDesenvolver funções para organizar e reutilizar código de forma eficiente;\nEfetuar operações de leitura e escrita de dados em diversos formatos de ficheiros (CSV, TXT, JSON);\nUtilizar a biblioteca Pandas para o carregamento, exploração inicial e manipulação de dados;\nCalcular e interpretar as principais estatísticas descritivas para caracterizar conjuntos de dados;\nAplicar técnicas avançadas de limpeza e preparação de dados utilizando a biblioteca Pandas;\nAplicar os conhecimentos adquiridos na resolução de problemas práticos e no desenvolvimento de um mini-projeto de manipulação e análise básica de dados;\nSelecionar o tipo de gráfico adequado ao objetivo analítico (distribuição, comparação, relação, composição, evolução);\nCriar visualizações estáticas informativas com Matplotlib e Seaborn, aplicando boas práticas de legibilidade e precisão;\nExplorar e comunicar relações e correlações entre variáveis (incluindo matrizes de correlação);\nPersonalizar gráficos (títulos, rótulos, escalas, anotações, layouts) e exportar com qualidade para relatório;\nConstruir dashboards simples e interativos em Streamlit para apresentar análises, indicadores e visualizações.",
        sponsorImgUrl: "Este curso é financiado por entidades e planos governamentais.",
        courseContent: "Nesta ação de formação, iremos apresentar um conjunto de conteúdos que proporcionarão aos formandos a oportunidade de adquirir competências essenciais para o seu desenvolvimento. Saiba aqui quais as temáticas que irão ser abordadas.",
        enrollment: "",
        hasDownloadButton: false
    }
];